apiVersion: apps/v1
kind: Deployment
metadata:
  name: b2cloud-assignment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: b2cloud-assignment
  template:
    metadata:
      labels:
        app: b2cloud-assignment
    spec:
      containers:
      - name: b2cloud-assignment-app
        image: 633154839293.dkr.ecr.eu-north-1.amazonaws.com/b2cloud-assignment/app:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m" 
            memory: "128Mi" 
          limits:
            cpu: "200m" 
            memory: "256Mi" 