apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world-deployment
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: hello-world-app
        image: 633154839293.dkr.ecr.eu-north-1.amazonaws.com/b2cloud-assignment/app:latest
        ports:
        - containerPort: 80