apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: b2cloud-assignment
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: b2cloud-assignment
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10