name: Build, Push, and Deploy to Kubernetes
on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.ACR_LOGIN_SERVER }}/b2cloud-assignment/app:${{ github.sha }}

  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push # This job depends on the previous one

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Kubeconfig
      run: |
        mkdir -p $HOME/.kube
        echo "${{ secrets.KUBE_CONFIG }}" | base64 --decode > $HOME/.kube/config
        chmod 600 $HOME/.kube/config

    - name: Update Kubernetes Manifest with Image Tag
      run: |
        sed -i 's|image:.*|image: ${{ secrets.ACR_LOGIN_SERVER }}/b2cloud-assignment/app:${{ github.sha }}|g' kubernetes/deployment.yml
        echo "Updated deployment.yml with new image tag"
        cat kubernetes/deployment.yml

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f kubernetes/deployment.yml
        echo "Waiting for deployment to complete..."
        kubectl rollout status deployment/hello-world-deployment --timeout=60s
        echo "Deployment successful!"